-- =====================================================
-- Seed Data - Vietnamese Provinces (63 provinces)
-- =====================================================
INSERT INTO provinces (name, slug) VALUES
    ('Hà Nội', 'ha-noi'),
    ('Hồ Chí Minh', 'ho-chi-minh'),
    ('Đà Nẵng', 'da-nang'),
    ('Hải Phòng', 'hai-phong'),
    ('Cần Thơ', 'can-tho'),
    ('An Giang', 'an-giang'),
    ('Bà Rịa - Vũng Tàu', 'ba-ria-vung-tau'),
    ('Bắc Giang', 'bac-giang'),
    ('Bắc Kạn', 'bac-kan'),
    ('Bạc Liêu', 'bac-lieu'),
    ('Bắc Ninh', 'bac-ninh'),
    ('Bến Tre', 'ben-tre'),
    ('Bình Định', 'binh-dinh'),
    ('Bình Dương', 'binh-duong'),
    ('Bình Phước', 'binh-phuoc'),
    ('Bình Thuận', 'binh-thuan'),
    ('Cà Mau', 'ca-mau'),
    ('Cao Bằng', 'cao-bang'),
    ('Đắk Lắk', 'dak-lak'),
    ('Đắk Nông', 'dak-nong'),
    ('Điện Biên', 'dien-bien'),
    ('Đồng Nai', 'dong-nai'),
    ('Đồng Tháp', 'dong-thap'),
    ('Gia Lai', 'gia-lai'),
    ('Hà Giang', 'ha-giang'),
    ('Hà Nam', 'ha-nam'),
    ('Hà Tĩnh', 'ha-tinh'),
    ('Hải Dương', 'hai-duong'),
    ('Hậu Giang', 'hau-giang'),
    ('Hòa Bình', 'hoa-binh'),
    ('Hưng Yên', 'hung-yen'),
    ('Khánh Hòa', 'khanh-hoa'),
    ('Kiên Giang', 'kien-giang'),
    ('Kon Tum', 'kon-tum'),
    ('Lai Châu', 'lai-chau'),
    ('Lâm Đồng', 'lam-dong'),
    ('Lạng Sơn', 'lang-son'),
    ('Lào Cai', 'lao-cai'),
    ('Long An', 'long-an'),
    ('Nam Định', 'nam-dinh'),
    ('Nghệ An', 'nghe-an'),
    ('Ninh Bình', 'ninh-binh'),
    ('Ninh Thuận', 'ninh-thuan'),
    ('Phú Thọ', 'phu-tho'),
    ('Phú Yên', 'phu-yen'),
    ('Quảng Bình', 'quang-binh'),
    ('Quảng Nam', 'quang-nam'),
    ('Quảng Ngãi', 'quang-ngai'),
    ('Quảng Ninh', 'quang-ninh'),
    ('Quảng Trị', 'quang-tri'),
    ('Sóc Trăng', 'soc-trang'),
    ('Sơn La', 'son-la'),
    ('Tây Ninh', 'tay-ninh'),
    ('Thái Bình', 'thai-binh'),
    ('Thái Nguyên', 'thai-nguyen'),
    ('Thanh Hóa', 'thanh-hoa'),
    ('Thừa Thiên Huế', 'thua-thien-hue'),
    ('Tiền Giang', 'tien-giang'),
    ('Trà Vinh', 'tra-vinh'),
    ('Tuyên Quang', 'tuyen-quang'),
    ('Vĩnh Long', 'vinh-long'),
    ('Vĩnh Phúc', 'vinh-phuc'),
    ('Yên Bái', 'yen-bai')
ON DUPLICATE KEY UPDATE name = VALUES(name);
